version: "3.9"

services:
  client:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: client
    environment:
      - SPRING_PROFILES_ACTIVE=qa
    ports:
      - "8001:8001"
    restart: unless-stopped
    networks:
      - public

networks:
  public: