spring:
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update